version: 2

aliases:
defaults: &defaults
    docker:
      - image: circleci/node:8
    working_directory: ~/crossroads/browse.goodcity
restore-repo-cache: &restore-repo-cache
    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
restore-yarn-cache: &restore-yarn-cache
    key: v1-yarn-packages-{{ checksum "yarn.lock" }}
save-yarn-cache: &save-yarn-cache
    key: v1-yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules
yarn: &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

restore-bower-cache: &restore-bower-cache
    key: v1-bower-components-{{ checksum "bower.json" }}
save-bower-cache: &save-bower-cache
    key: v1-bower-components-{{ checksum "bower.json" }}
    paths:
      - bower_components

restore-bundle-cache: &restore-bundle-cache
    key: v1-bundle-{{ checksum "Gemfile.lock" }}
save-bundle-cache: &save-bundle-cache
    key: v1-bundle-{{ checksum "Gemfile.lock" }}
    paths:
        - vendor/bundle

jobs:
  checkout_code:
    <<: *defaults

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/crossroads/browse.goodcity

  package_dependencies:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.1-node

    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - restore-cache: *restore-bower-cache
      - run: yarn run bower install
      - save-cache: *save-bower-cache

  test_cases:
    <<: *defaults

    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Start Ember test server
          command: yarn run ember server --port 4202
          background: true
      - run:
          name: Wait for Ember test server to start
          command: dockerize -wait tcp://localhost:4202 -timeout 1m
      - run:
          name: Run Ember tests
          command: COVERAGE=true yarn run ember test
          environment:
            COVERAGE: true
      - persist_to_workspace:
          root: .
          paths:
            - coverage*/lcov.info

  upload-coverage:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - attach_workspace:
          at: ~/crossroads/browse.goodcity
      - run:
          name: Upload coverage results to Code Climate
          command: |
            yarn run codeclimate-test-reporter < coverage*/lcov.info

  www_build:
    <<: *defaults
    environment:
      EMBER_CLI_CORDOVA: "0"
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Set Environment variables
          command: |
            echo 'export APP_SHA=$(echo $CIRCLE_SHA1 | cut -c1-7)' >> $BASH_ENV
            echo 'export staging=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo false; else echo true; fi)' >> $BASH_ENV
      - run:
          name: Print Environment variables
          command: |
            echo APP_SHA=$APP_SHA
            echo EMBER_CLI_CORDOVA=$EMBER_CLI_CORDOVA
            echo staginng=$staging
      - run: yarn run ember build --environment=production
      - run: mv dist/ dist-www
      - persist_to_workspace:
          root: .
          paths:
            - dist-www/

  www-deploy:
    <<: *defaults

    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-bundle-cache
      - run: bundle check --path=vendor/bundle || bundle install --deployment --jobs=4 --retry=3
      - save-cache: *save-bundle-cache
      - attach_workspace:
          at: ~/crossroads/browse.goodcity
      - run: mv dist-www/ dist
      - run:
          name: Setup Environment
          command: |
            echo 'export STAGE=$(if [ "$CIRCLE_BRANCH" == "live" ]; then echo production; else echo staging; fi)' >> $BASH_ENV
            echo 'export APP_VERSION=$(jq -r ".version" package.json)' >> $BASH_ENV
      - run:
          name: Print Environment Variables
          command: |
            echo STAGE=$STAGE
            echo APP_VERSION=$APP_VERSION
      - run: bundle exec cap $STAGE deploy:upload

  ember_cordova_build:
    <<: *defaults
    environment:
        EMBER_CLI_CORDOVA: "1"
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Setup Environment variables
          command: |
            echo 'export APP_SHA=$(echo $CIRCLE_SHA1 | cut -c1-7)' >> $BASH_ENV
            echo 'export APP_VERSION=$(jq -r ".version" package.json)' >> $BASH_ENV
      - run:
          name: Print Environment variables
          command: |
              echo EMBER_CLI_CORDOVA=$EMBER_CLI_CORDOVA
              echo APP_SHA=$APP_SHA
              echo staging=$staging
              echo APP_VERSION=$APP_VERSION
      - run: yarn run ember build --environment=production
      - run: mv dist/ cordova/www
      - persist_to_workspace:
          root: .
          paths:
            - cordova/www

workflows:
    version: 2
    build_and_bundle:
      jobs:
        - checkout_code
        - package_dependencies:
            requires:
              - checkout_code
        - test_cases:
            requires:
              - package_dependencies
        - upload-coverage:
            requires:
              - package_dependencies
              - test_cases
        - www_build:
            requires:
              - upload-coverage
        - www-deploy:
            requires:
              - www_build
