version: 2

aliases:
defaults: &defaults
    docker:
      - image: circleci/node:boron
    working_directory: ~/browse.goodcity
restore-repo-cache: &restore-repo-cache
    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
restore-yarn-cache: &restore-yarn-cache
    key: v1-yarn-packages-{{ checksum "yarn.lock" }}
save-yarn-cache: &save-yarn-cache
    key: v1-yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - node_modules
yarn: &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

restore-bower-cache: &restore-bower-cache
    key: v1-bower-components-{{ checksum "bower.json" }}
save-bower-cache: &save-bower-cache
    key: v1-bower-components-{{ checksum "bower.json" }}
    paths:
      - bower_components

restore-bundle-cache: &restore-bundle-cache
    key: v1-bundle-{{ checksum "Gemfile.lock" }}
save-bundle-cache: &save-bundle-cache
    key: v1-bundle-{{ checksum "Gemfile.lock" }}
    paths:
        - vendor/bundle

jobs:
  checkout_code:
    <<: *defaults

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/browse.goodcity

  package_dependencies:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.1-node

    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache
      - restore-cache: *restore-bower-cache
      - run: yarn run bower install
      - save-cache: *save-bower-cache

  test_cases:
    <<: *defaults

    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - run:
          name: Start Ember test server
          command: yarn run ember server --port 4202
          background: true
      - run:
          name: Wait for Ember test server to start
          command: dockerize -wait tcp://localhost:4202 -timeout  1m
      - run:
          name: Run Ember tests
          command: COVERAGE=true yarn run ember test
      - persist_to_workspace:
          root: .
          paths:
            - coverage*/lcov.info

  upload-coverage:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - restore-cache: *restore-bower-cache
      - attach_workspace:
          at: ~/browse.goodcity
      - run:
          name: Upload coverage results to Code Climate
          command: |
            yarn run codeclimate-test-reporter < coverage*/lcov.info

workflows:
    version: 2
    build_and_bundle:
      jobs:
        - checkout_code
        - package_dependencies:
            requires:
              - checkout_code
        - test_cases:
            requires:
              - package_dependencies
        - upload-coverage:
            requires:
              - package_dependencies
              - test_cases
