version: 2

aliases:
defaults: &defaults
    docker:
      - image: circleci/node:boron
    working_directory: ~/browse.goodcity

jobs:
  checkout_code:
    <<: *defaults

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/browse.goodcity

workflows:
    version: 2
    build_and_bundle:
      jobs:
        - checkout_code
